<a href="https://colab.research.google.com/github/ML-brooowss/ML/blob/main/matrix_factorisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Library
# !pip install sentence-transformers
# !pip install joblib
# !pip install collections
from collections import defaultdict
from joblib import Parallel, delayed
import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import TfidfVectorizer
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
import os


# Recommender Systems
| Recommender Type     | Similarity Between | Based On           | Example Statement                                      |
|----------------------|--------------------|--------------------|--------------------------------------------------------|
| CF – Item-Item       | Items              | User behavior      | “You liked A, others who liked A also liked B”         |
| CF – User-User       | Users              | User behavior      | “People like you liked B, so you might too”            |
| Content-Based        | Items              | Item text/content  | “These books are similar in description/topic”         |
| Hybrid               | Items              | Content + Behavior | “You liked A; B is similar and liked by others too”    |


### Task 1: Exploring



#### Step 1:Get the data

In [ ]:
# Load the datasets

interactions = pd.read_csv('https://raw.githubusercontent.com/linneverh/MachineLearning/main/interactions_train.csv')

#FOR: Google enhanced & ISBN enhanced - author_date_title_subjects priority
items1 = pd.read_csv("https://media.githubusercontent.com/media/ML-brooowss/ML/refs/heads/main/final_items/author_date_title_subjects/embeddings_part1.csv")
items2 = pd.read_csv("https://media.githubusercontent.com/media/ML-brooowss/ML/refs/heads/main/final_items/author_date_title_subjects/embeddings_part2.csv")
items = pd.concat([items1, items2])

#rename columns
interactions = interactions.rename(columns={'u': 'user_id', 'i': 'book_id', 't': 'timestamp'})
items=items.rename(columns={'i':'book_id'})

# Display the first rows of the updated interactions DataFrame
display(interactions.head())
display(items.head())

# Display the first rows of each dataset
display(interactions.head())
display(items.head())

user_id  book_id     timestamp
0     4456     8581  1.687541e+09
1      142     1964  1.679585e+09
2      362     3705  1.706872e+09
3     1809    11317  1.673533e+09
4     4384     1323  1.681402e+09

Unnamed: 0                                      CanonicalLink  \
0         723  https://books.google.com/books/about/Classific...   
1         724  https://books.google.com/books/about/Les_inter...   
2         725  https://books.google.com/books/about/Histoire_...   
3         726  https://books.google.com/books/about/Ce_livre_...   
4         727  https://books.google.com/books/about/Le_grand_...   

                                         Description           ISBN  \
0                                                NaN  9782871303336   
1  C'est dans l'interaction en classe que s'actua...  9782278058327   
2  Depuis la parution en 1918 de l'ouvrage fondat...     2343190194   
3  Juin 1940. Les Allemands entrent dans Paris.Pa...  9782365350020   
4  Trois histoires d'amour, un lanceur d'alerte, ...  9782702180815   

                                           ImageLink Language  PublishedDate  \
0  https://images.isbndb.com/covers/2000472348298...       fr         2012.0   
1  https://images.isbndb.com/covers/2384333482926...       fr         2011.0   
2  http://books.google.com/books/content?id=Q2PMD...       fr         2020.0   
3  https://images.isbndb.com/covers/1994518348298...       fr         2012.0   
4  http://books.google.com/books/content?id=f5u3z...       fr         1984.0   

      Publisher                                           Subjects  \
0   Ed du CEFAL  Classification décimale universelle; Indexatio...   
1        Didier  didactique--langue étrangère - enseignement; d...   
2   L'Harmattan  Histoires de vie en sociologie; Sciences socia...   
3       Vraoum!  Moyen-Orient; Bandes dessinées autobiographiqu...   
4  Calmann-Lévy  France--1945-1975; Roman historique; Roman fra...   

                                               Title  ... book_id  \
0  Classification décimale universelle : édition ...  ...       0   
1  Les interactions dans l'enseignement des langu...  ...       1   
2  Histoire de vie et recherche biographique : pe...  ...       2   
3  Ce livre devrait me permettre de résoudre le c...  ...       3   
4                    Les années glorieuses : roman /  ...       4   

                                         title_clean  \
0  Classification décimale universelle : édition ...   
1  Les interactions dans l'enseignement des langu...   
2  Histoire de vie et recherche biographique : pe...   
3  Ce livre devrait me permettre de résoudre le c...   
4                      Les années glorieuses : roman   

                                   title_description  \
0  Classification décimale universelle : édition ...   
1  Les interactions dans l'enseignement des langu...   
2  Histoire de vie et recherche biographique : pe...   
3  Ce livre devrait me permettre de résoudre le c...   
4  Les années glorieuses : roman Trois histoires ...   

                              date_title_description  \
0  2012 Classification décimale universelle : édi...   
1  2011 Les interactions dans l'enseignement des ...   
2  2020 Histoire de vie et recherche biographique...   
3  2012 Ce livre devrait me permettre de résoudre...   
4  1984 Les années glorieuses : roman Trois histo...   

                            author_title_description  \
0  UDC Consortium (The Hague) Classification déci...   
1  Cicurel, Francine, Les interactions dans l'ens...   
2  Aneta Slowik, Hervé Breton, Gaston Pineau Hist...   
3  Mazas, Sylvain, Ce livre devrait me permettre ...   
4  Lemaitre, Pierre, Les années glorieuses : roma...   

                       author_date_title_description  \
0  UDC Consortium (The Hague) 2012 Classification...   
1  Cicurel, Francine, 2011 Les interactions dans ...   
2  Aneta Slowik, Hervé Breton, Gaston Pineau 2020...   
3  Mazas, Sylvain, 2012 Ce livre devrait me perme...   
4  Lemaitre, Pierre, 1984 Les années glorieuses :...   

                                   author_date_title  \
0  UDC Consortium (The Hague) 2012 Classification...   
1  Cicurel, Francine, 2011 Les interactions dans ... 

user_id  book_id     timestamp
0     4456     8581  1.687541e+09
1      142     1964  1.679585e+09
2      362     3705  1.706872e+09
3     1809    11317  1.673533e+09
4     4384     1323  1.681402e+09

Unnamed: 0                                      CanonicalLink  \
0         723  https://books.google.com/books/about/Classific...   
1         724  https://books.google.com/books/about/Les_inter...   
2         725  https://books.google.com/books/about/Histoire_...   
3         726  https://books.google.com/books/about/Ce_livre_...   
4         727  https://books.google.com/books/about/Le_grand_...   

                                         Description           ISBN  \
0                                                NaN  9782871303336   
1  C'est dans l'interaction en classe que s'actua...  9782278058327   
2  Depuis la parution en 1918 de l'ouvrage fondat...     2343190194   
3  Juin 1940. Les Allemands entrent dans Paris.Pa...  9782365350020   
4  Trois histoires d'amour, un lanceur d'alerte, ...  9782702180815   

                                           ImageLink Language  PublishedDate  \
0  https://images.isbndb.com/covers/2000472348298...       fr         2012.0   
1  https://images.isbndb.com/covers/2384333482926...       fr         2011.0   
2  http://books.google.com/books/content?id=Q2PMD...       fr         2020.0   
3  https://images.isbndb.com/covers/1994518348298...       fr         2012.0   
4  http://books.google.com/books/content?id=f5u3z...       fr         1984.0   

      Publisher                                           Subjects  \
0   Ed du CEFAL  Classification décimale universelle; Indexatio...   
1        Didier  didactique--langue étrangère - enseignement; d...   
2   L'Harmattan  Histoires de vie en sociologie; Sciences socia...   
3       Vraoum!  Moyen-Orient; Bandes dessinées autobiographiqu...   
4  Calmann-Lévy  France--1945-1975; Roman historique; Roman fra...   

                                               Title  ... book_id  \
0  Classification décimale universelle : édition ...  ...       0   
1  Les interactions dans l'enseignement des langu...  ...       1   
2  Histoire de vie et recherche biographique : pe...  ...       2   
3  Ce livre devrait me permettre de résoudre le c...  ...       3   
4                    Les années glorieuses : roman /  ...       4   

                                         title_clean  \
0  Classification décimale universelle : édition ...   
1  Les interactions dans l'enseignement des langu...   
2  Histoire de vie et recherche biographique : pe...   
3  Ce livre devrait me permettre de résoudre le c...   
4                      Les années glorieuses : roman   

                                   title_description  \
0  Classification décimale universelle : édition ...   
1  Les interactions dans l'enseignement des langu...   
2  Histoire de vie et recherche biographique : pe...   
3  Ce livre devrait me permettre de résoudre le c...   
4  Les années glorieuses : roman Trois histoires ...   

                              date_title_description  \
0  2012 Classification décimale universelle : édi...   
1  2011 Les interactions dans l'enseignement des ...   
2  2020 Histoire de vie et recherche biographique...   
3  2012 Ce livre devrait me permettre de résoudre...   
4  1984 Les années glorieuses : roman Trois histo...   

                            author_title_description  \
0  UDC Consortium (The Hague) Classification déci...   
1  Cicurel, Francine, Les interactions dans l'ens...   
2  Aneta Slowik, Hervé Breton, Gaston Pineau Hist...   
3  Mazas, Sylvain, Ce livre devrait me permettre ...   
4  Lemaitre, Pierre, Les années glorieuses : roma...   

                       author_date_title_description  \
0  UDC Consortium (The Hague) 2012 Classification...   
1  Cicurel, Francine, 2011 Les interactions dans ...   
2  Aneta Slowik, Hervé Breton, Gaston Pineau 2020...   
3  Mazas, Sylvain, 2012 Ce livre devrait me perme...   
4  Lemaitre, Pierre, 1984 Les années glorieuses :...   

                                   author_date_title  \
0  UDC Consortium (The Hague) 2012 Classification...   
1  Cicurel, Francine, 2011 Les interactions dans ... 


#### Step 2: Check the Number of interactions, users and movies

In [ ]:
n_users = interactions.user_id.nunique()
n_items = items.book_id.nunique()
print(f'Number of users = {n_users}, \n Number of books = {n_items} \n Number of interactions = {len(interactions)}')


Number of users = 7838, 
 Number of books = 15291 
 Number of interactions = 87047


In [ ]:
n_items = items.book_id.nunique()
print(f'Number of books = {n_items}')

Number of books = 15291



#### Step 3: Split the Data into Training and Test Sets

In [ ]:
# let's first sort the interactions by user and time stamp
interactions = interactions.sort_values(["user_id", "timestamp"])
interactions.head(100)

user_id  book_id     timestamp
21035        0        0  1.680191e+09
28842        0        1  1.680783e+09
3958         0        2  1.680801e+09
29592        0        3  1.683715e+09
6371         0        3  1.683715e+09
...        ...      ...           ...
20068        2       53  1.694861e+09
12721        2       53  1.695226e+09
86745        2       53  1.695226e+09
19329        2       53  1.695226e+09
79240        2       76  1.697288e+09

[100 rows x 3 columns]

In [ ]:
interactions["pct_rank"] = interactions.groupby("user_id")["timestamp"].rank(pct=True, method='dense')
interactions.reset_index(inplace=True, drop=True)
interactions.head(10)

user_id  book_id     timestamp  pct_rank
0        0        0  1.680191e+09      0.04
1        0        1  1.680783e+09      0.08
2        0        2  1.680801e+09      0.12
3        0        3  1.683715e+09      0.16
4        0        3  1.683715e+09      0.20
5        0        4  1.686569e+09      0.24
6        0        5  1.687014e+09      0.28
7        0        6  1.687014e+09      0.32
8        0        7  1.687014e+09      0.36
9        0        8  1.687260e+09      0.40

Now all remains to do is to pick the first 80% of the interactions of each user in the training set and the rest in the test set. We can do so using the `pct_rank` column.

In [ ]:
train_data = interactions[interactions["pct_rank"] < 0.8]
test_data = interactions[interactions["pct_rank"] >= 0.8]

In [ ]:
print("Training set size:", train_data.shape[0])
print("Testing set size:", test_data.shape[0])

Training set size: 65419
Testing set size: 21628


### Task 2: Creating User-Item Matrices for Implicit Feedback


In [ ]:
print('number of users =', n_users, '| number of movies =', n_items)

number of users = 7838 | number of movies = 15291


#### Step 1: Define the Function to Create the Data Matrix


In [ ]:
# Define a function to create the data matrix
def create_data_matrix(data, n_users, n_items):
    """
    This function returns a numpy matrix with shape (n_users, n_items).
    Each entry is a binary value indicating positive interaction.
    """
    data_matrix = np.zeros((n_users, n_items))
    data_matrix[data["user_id"].values, data["book_id"].values] = 1
    return data_matrix

#### Step 2: Create the Training and Testing Matrices

Now we can use the function to create matrices for both the training and testing data. Each cell in the matrix will show a 1 if there was a positive interaction in the training or testing data, and a 0 otherwise.

In [ ]:
entire_data=create_data_matrix(interactions, n_users, n_items)

In [ ]:
# Create the training and testing matrices
train_data_matrix = create_data_matrix(train_data, n_users, n_items)
test_data_matrix = create_data_matrix(test_data, n_users, n_items)

# Display the matrices to understand their structure
print('train_data_matrix')
print(train_data_matrix)
print("number of non-zero values: ", np.sum(train_data_matrix))
print('test_data_matrix')
print(test_data_matrix)
print("number of non-zero values: ", np.sum(test_data_matrix))


train_data_matrix
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
number of non-zero values:  49689.0
test_data_matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
number of non-zero values:  19409.0


In [ ]:
#give the dimensions of matrices
print("Train data matrix dimensions:", train_data_matrix.shape)
print("Test data matrix dimensions:", test_data_matrix.shape)

Train data matrix dimensions: (7838, 15291)
Test data matrix dimensions: (7838, 15291)


#### Basic Definitions

In [ ]:
# Recommendation frame generation
def create_recommendation_table(user_predictions, top_n=10, separator=" "):
    """
    Creates a table of top-N recommendations for each user.

    Args:
        user_predictions (numpy.ndarray): Rows = users, columns = items. Predicted scores.
        top_n (int): Number of top recommendations per user.
        separator (str): Delimiter to join recommended book IDs.

    Returns:
        pandas.DataFrame: Columns = ['user_id', 'recommendation'].
    """
    recommendations = []
    num_users = user_predictions.shape[0]

    for user_id in range(num_users):
        top_items = np.argsort(user_predictions[user_id, :])[-top_n:][::-1]
        recommendations.append({
            'user_id': user_id,
            'recommendation': separator.join(map(str, top_items))
        })

    return pd.DataFrame(recommendations)

In [ ]:
# Def for the precision_recall_at_k function
def precision_recall_at_k(prediction, ground_truth, k=10):
    """
    Calculates Precision@K and Recall@K for top-K recommendations.
    Parameters:
        prediction (numpy array): The predicted interaction matrix with scores.
        ground_truth (numpy array): The ground truth interaction matrix (binary).
        k (int): Number of top recommendations to consider.
    Returns:
        precision_at_k (float): The average precision@K over all users.
        recall_at_k (float): The average recall@K over all users.
    """
    num_users = prediction.shape[0]
    precision_at_k, recall_at_k = 0, 0

    for user in range(num_users):
        # TODO: Get the indices of the top-K items for the user based on predicted scores
        top_k_items = np.argsort(prediction[user, :])[-k:]

        # TODO: Calculate the number of relevant items in the top-K items for the user
        relevant_items_in_top_k = np.isin(top_k_items, np.where(ground_truth[user, :] == 1)[0]).sum()

        # TODO: Calculate the total number of relevant items for the user
        total_relevant_items = ground_truth[user, :].sum()

        # Precision@K and Recall@K for this user
        precision_at_k += relevant_items_in_top_k / k
        recall_at_k += relevant_items_in_top_k / total_relevant_items if total_relevant_items > 0 else 0

    # Average Precision@K and Recall@K over all users
    precision_at_k /= num_users
    recall_at_k /= num_users

    return precision_at_k, recall_at_k

In [ ]:
# Create random splits def.
def random_split_per_user(interactions_df, test_size=0.2):
    train_list = []
    test_list = []
    for user_id, user_df in interactions_df.groupby('user_id'):
        train_df, test_df = train_test_split(user_df, test_size=test_size)
        train_list.append(train_df)
        test_list.append(test_df)
    return pd.concat(train_list), pd.concat(test_list)

In [ ]:
# Define the function to predict interactions based on item similarity
def item_based_predict(interactions, similarity, epsilon=1e-9):
    """
    Predicts user-item interactions based on item-item similarity.
    Parameters:
        interactions (numpy array): The user-item interaction matrix.
        similarity (numpy array): The item-item similarity matrix.
        epsilon (float): Small constant added to the denominator to avoid division by zero.
    Returns:
        numpy array: The predicted interaction scores for each user-item pair.
    """
    # np.dot does the matrix multiplication. Here we are calculating the
    # weighted sum of interactions based on item similarity
    pred = similarity.dot(interactions.T) / (similarity.sum(axis=1)[:, np.newaxis] + epsilon)
    return pred.T  # Transpose to get users as rows and items as columns

#### Matrix factorisation prediction

In [ ]:
# #Matrix factorisation prediction
def matrix_factorization(interactions_df, K=20, steps=50, alpha=0.01, beta=0.01):
    """
    Matrix factorization using SGD for implicit feedback (binary interactions).
    Params:
        interactions_df: DataFrame with ['user_id', 'book_id']
        K: number of latent features
        steps: SGD iterations
        alpha: learning rate
        beta: regularization term
    Returns:
        P, Q: latent feature matrices for users and items
        R_hat: predicted interaction scores
    """
    user_ids = interactions_df['user_id'].unique()
    book_ids = interactions_df['book_id'].unique()

    user_map = {uid: idx for idx, uid in enumerate(user_ids)}
    book_map = {bid: idx for idx, bid in enumerate(book_ids)}

    n_users = len(user_ids)
    n_books = len(book_ids)

    P = np.random.rand(n_users, K)
    Q = np.random.rand(n_books, K)

    R = np.zeros((n_users, n_books))
    for _, row in interactions_df.iterrows():
        u_idx = user_map[row['user_id']]
        b_idx = book_map[row['book_id']]
        R[u_idx, b_idx] = 1

    for step in range(steps):
        for i in range(n_users):
            for j in range(n_books):
                if R[i, j] > 0:
                    eij = R[i, j] - np.dot(P[i, :], Q[j, :])
                    P[i, :] += alpha * (eij * Q[j, :] - beta * P[i, :])
                    Q[j, :] += alpha * (eij * P[i, :] - beta * Q[j, :])

    R_hat = np.dot(P, Q.T)
    return P, Q, R_hat

In [ ]:
P, Q, prediction_matrix = matrix_factorization(interactions[['user_id', 'book_id']])

In [ ]:
# Step 1: Recreate user_map and item_map
user_ids = interactions['user_id'].unique()
book_ids = interactions['book_id'].unique()

user_map = {uid: idx for idx, uid in enumerate(user_ids)}
item_map = {iid: idx for idx, iid in enumerate(book_ids)}
user_map_inv = {v: k for k, v in user_map.items()}
item_map_inv = {v: k for k, v in item_map.items()}

# Step 2: Generate recommendations as a DataFrame
def generate_recommendation_dataframe(pred_matrix, interactions_df, user_map, item_map, N=10):
    user_map_inv = {v: k for k, v in user_map.items()}
    item_map_inv = {v: k for k, v in item_map.items()}

    recommendations = []

    for user_idx in range(pred_matrix.shape[0]):
        user_id = user_map_inv[user_idx]
        scores = pred_matrix[user_idx].copy()

        # Exclude already interacted items
        interacted = interactions_df[interactions_df['user_id'] == user_id]['book_id'].values
        interacted_idx = [item_map[i] for i in interacted if i in item_map]
        scores[interacted_idx] = -np.inf

        # Top-N predictions
        top_items = np.argsort(scores)[-N:][::-1]
        top_book_ids = [item_map_inv[i] for i in top_items]
        recommendations.append([user_id] + top_book_ids)

    columns = ['user_id'] + [f'top_{i+1}' for i in range(N)]
    return pd.DataFrame(recommendations, columns=columns)

# Step 3: Run it
recommendation_df = generate_recommendation_dataframe(prediction_matrix, interactions, user_map, item_map, N=10)
recommendation_df.head()

# Step 4: Save to csv
recommendation_df['recommendation'] = recommendation_df[[f'top_{i+1}' for i in range(10)]].astype(str).agg(' '.join, axis=1)
final_df = recommendation_df[['user_id', 'recommendation']]
final_df.to_csv('hybrid_recommendations.csv', index=False)


user_id  top_1  top_2  top_3  top_4  top_5  top_6  top_7  top_8  top_9  \
0        0   1149   9739  11416   8279  10770  14623  11522  14630   2975   
1        1  10928  14601  14149   3992   7160   1272  14665  12126   9326   
2        2   3783   2444   7534   8279  11521  10770   5432   3211   9240   
3        3  11452   6283  14544   8563   4708   3507  14758   6698   1819   
4        4   3133  14956   5262   7406   1105   6452  12368   6530  13394   

   top_10  
0   11831  
1    9635  
2    4429  
3   12737  
4   10147